# API Extensions for Phase V
# Branch: 005-cloud-native-doks
# Version: 1.0.0

openapi: "3.1.0"
info:
  title: Todo Chatbot API - Phase V Extensions
  version: "1.0.0"
  description: |
    New and modified API endpoints for Phase V cloud-native features.
    Extends the existing Phase IV API with recurrence and notification support.

servers:
  - url: https://api.todo.example.com/v1
    description: Production API

paths:
  # Extended Task Endpoints
  /tasks:
    post:
      summary: Create a new task (extended with recurrence)
      operationId: createTask
      tags: [Tasks]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateTaskRequest"
      responses:
        "201":
          description: Task created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TaskResponse"
        "400":
          $ref: "#/components/responses/BadRequest"
        "401":
          $ref: "#/components/responses/Unauthorized"

  /tasks/{taskId}:
    parameters:
      - $ref: "#/components/parameters/TaskId"
    patch:
      summary: Update a task (extended with recurrence)
      operationId: updateTask
      tags: [Tasks]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateTaskRequest"
      responses:
        "200":
          description: Task updated successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TaskResponse"
        "400":
          $ref: "#/components/responses/BadRequest"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "404":
          $ref: "#/components/responses/NotFound"

  /tasks/{taskId}/complete:
    parameters:
      - $ref: "#/components/parameters/TaskId"
    post:
      summary: Mark task as completed (triggers recurring task creation)
      operationId: completeTask
      tags: [Tasks]
      description: |
        Marks the task as completed. If the task has a recurrence pattern,
        a `task.completed` event is published which triggers the recurring-task
        service to create the next instance.
      responses:
        "200":
          description: Task completed successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  task:
                    $ref: "#/components/schemas/TaskResponse"
                  nextInstance:
                    type: object
                    nullable: true
                    description: If recurring, info about next instance (async creation)
                    properties:
                      scheduledFor:
                        type: string
                        format: date-time
        "401":
          $ref: "#/components/responses/Unauthorized"
        "404":
          $ref: "#/components/responses/NotFound"

  # Recurrence Endpoints
  /tasks/{taskId}/recurrence:
    parameters:
      - $ref: "#/components/parameters/TaskId"
    get:
      summary: Get task recurrence pattern
      operationId: getTaskRecurrence
      tags: [Recurrence]
      responses:
        "200":
          description: Recurrence pattern retrieved
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RecurrencePattern"
        "404":
          description: Task not found or has no recurrence

    put:
      summary: Set or update task recurrence pattern
      operationId: setTaskRecurrence
      tags: [Recurrence]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RecurrencePattern"
      responses:
        "200":
          description: Recurrence pattern updated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RecurrencePattern"
        "400":
          $ref: "#/components/responses/BadRequest"

    delete:
      summary: Remove recurrence from task
      operationId: removeTaskRecurrence
      tags: [Recurrence]
      responses:
        "204":
          description: Recurrence removed
        "404":
          $ref: "#/components/responses/NotFound"

  /tasks/{taskId}/instances:
    parameters:
      - $ref: "#/components/parameters/TaskId"
    get:
      summary: Get all instances of a recurring task
      operationId: getRecurringInstances
      tags: [Recurrence]
      parameters:
        - name: status
          in: query
          schema:
            type: string
            enum: [pending, completed, all]
            default: all
        - name: limit
          in: query
          schema:
            type: integer
            default: 50
            maximum: 100
      responses:
        "200":
          description: List of task instances
          content:
            application/json:
              schema:
                type: object
                properties:
                  parentTaskId:
                    type: string
                    format: uuid
                  instances:
                    type: array
                    items:
                      $ref: "#/components/schemas/TaskResponse"
                  total:
                    type: integer

  # Notification Preferences
  /users/me/notifications:
    get:
      summary: Get notification preferences
      operationId: getNotificationPreferences
      tags: [Notifications]
      responses:
        "200":
          description: Notification preferences retrieved
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NotificationPreferences"

    patch:
      summary: Update notification preferences
      operationId: updateNotificationPreferences
      tags: [Notifications]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateNotificationPreferences"
      responses:
        "200":
          description: Preferences updated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NotificationPreferences"

  /tasks/{taskId}/reminder:
    parameters:
      - $ref: "#/components/parameters/TaskId"
    get:
      summary: Get task reminder settings
      operationId: getTaskReminder
      tags: [Notifications]
      responses:
        "200":
          description: Reminder settings retrieved
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ReminderSettings"

    patch:
      summary: Update task reminder settings
      operationId: updateTaskReminder
      tags: [Notifications]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateReminderSettings"
      responses:
        "200":
          description: Reminder updated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ReminderSettings"

  # Health & Observability
  /health:
    get:
      summary: Service health check
      operationId: healthCheck
      tags: [Operations]
      responses:
        "200":
          description: Service is healthy
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HealthResponse"

  /health/ready:
    get:
      summary: Readiness probe (dependencies checked)
      operationId: readinessCheck
      tags: [Operations]
      responses:
        "200":
          description: Service is ready
        "503":
          description: Service is not ready (dependencies unavailable)

components:
  parameters:
    TaskId:
      name: taskId
      in: path
      required: true
      schema:
        type: string
        format: uuid

  schemas:
    CreateTaskRequest:
      type: object
      required:
        - title
      properties:
        title:
          type: string
          maxLength: 255
        description:
          type: string
          nullable: true
        dueDate:
          type: string
          format: date-time
          nullable: true
        reminderOffset:
          type: integer
          default: 30
          description: Minutes before due date for reminder
        recurrence:
          $ref: "#/components/schemas/RecurrencePattern"
          nullable: true

    UpdateTaskRequest:
      type: object
      properties:
        title:
          type: string
          maxLength: 255
        description:
          type: string
          nullable: true
        dueDate:
          type: string
          format: date-time
          nullable: true
        status:
          type: string
          enum: [pending, completed]
        reminderOffset:
          type: integer
        recurrence:
          $ref: "#/components/schemas/RecurrencePattern"
          nullable: true

    TaskResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
        title:
          type: string
        description:
          type: string
          nullable: true
        status:
          type: string
          enum: [pending, completed, deleted]
        dueDate:
          type: string
          format: date-time
          nullable: true
        reminderOffset:
          type: integer
        hasRecurrence:
          type: boolean
        recurrence:
          $ref: "#/components/schemas/RecurrencePattern"
          nullable: true
        parentTaskId:
          type: string
          format: uuid
          nullable: true
          description: If this is a recurring instance, the original task ID
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

    RecurrencePattern:
      type: object
      required:
        - frequency
      properties:
        frequency:
          type: string
          enum: [daily, weekly, monthly, custom]
        interval:
          type: integer
          minimum: 1
          default: 1
          description: Every N frequency units
        byWeekday:
          type: array
          items:
            type: integer
            minimum: 0
            maximum: 6
          description: Days of week (0=Monday, 6=Sunday)
        byMonthday:
          type: integer
          minimum: 1
          maximum: 31
          description: Day of month
        endDate:
          type: string
          format: date-time
          nullable: true
          description: When recurrence stops (mutually exclusive with maxOccurrences)
        maxOccurrences:
          type: integer
          minimum: 1
          nullable: true
          description: Max instances to create (mutually exclusive with endDate)
        rruleString:
          type: string
          description: RFC 5545 RRULE for custom patterns

    NotificationPreferences:
      type: object
      properties:
        emailEnabled:
          type: boolean
          default: true
        pushEnabled:
          type: boolean
          default: true
        quietHoursStart:
          type: string
          format: time
          nullable: true
          example: "22:00"
        quietHoursEnd:
          type: string
          format: time
          nullable: true
          example: "08:00"
        defaultReminderOffset:
          type: integer
          default: 30
          description: Default minutes before due date

    UpdateNotificationPreferences:
      type: object
      properties:
        emailEnabled:
          type: boolean
        pushEnabled:
          type: boolean
        quietHoursStart:
          type: string
          format: time
          nullable: true
        quietHoursEnd:
          type: string
          format: time
          nullable: true
        defaultReminderOffset:
          type: integer

    ReminderSettings:
      type: object
      properties:
        taskId:
          type: string
          format: uuid
        enabled:
          type: boolean
          default: true
        offsetMinutes:
          type: integer
          default: 30
        channels:
          type: array
          items:
            type: string
            enum: [email, push]
          default: [email, push]
        scheduledFor:
          type: string
          format: date-time
          nullable: true
          description: When reminder will trigger (computed from dueDate - offset)

    UpdateReminderSettings:
      type: object
      properties:
        enabled:
          type: boolean
        offsetMinutes:
          type: integer
        channels:
          type: array
          items:
            type: string
            enum: [email, push]

    HealthResponse:
      type: object
      properties:
        status:
          type: string
          enum: [healthy, degraded, unhealthy]
        version:
          type: string
        timestamp:
          type: string
          format: date-time
        checks:
          type: object
          additionalProperties:
            type: object
            properties:
              status:
                type: string
                enum: [up, down]
              latencyMs:
                type: integer

    ErrorResponse:
      type: object
      required:
        - error
        - message
      properties:
        error:
          type: string
          description: Error code
        message:
          type: string
          description: Human-readable message
        details:
          type: object
          additionalProperties: true
        correlationId:
          type: string
          description: Dapr correlation ID for tracing

  responses:
    BadRequest:
      description: Invalid request
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"
          example:
            error: "VALIDATION_ERROR"
            message: "Invalid recurrence pattern: cannot set both endDate and maxOccurrences"

    Unauthorized:
      description: Authentication required
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"
          example:
            error: "UNAUTHORIZED"
            message: "Invalid or expired token"

    NotFound:
      description: Resource not found
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"
          example:
            error: "NOT_FOUND"
            message: "Task not found"

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: Better Auth JWT token

security:
  - bearerAuth: []

tags:
  - name: Tasks
    description: Task CRUD operations (extended)
  - name: Recurrence
    description: Recurring task management
  - name: Notifications
    description: Notification preferences and reminders
  - name: Operations
    description: Health checks and observability
